version: '3'

services:
  neo4j:
    image: neo4j:latest
    container_name: 'NEO4J_COMPUTER_MAINTENANCE'
    hostname: neo4j
    container_name: neo4j
    ports:
      - "7473:7473"
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./neo4j/data:/data
    environment:
      - NEO4J_dbms_default__listen__address=0.0.0.0
      - NEO4J_dbms_default__advertised__address=neo4j
      - NEO4J_dbms_connector_bolt_advertised__address=:57687
      - NEO4J_dbms_ssl_policy_bolt_client__auth=NONE
      - NEO4J_dbms_ssl_policy_https_client__auth=NONE
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=none

  server:
    container_name: 'NODEJS_COMPUTER_MAINTENANCE'
    build: .
    environment:
      NODE_ENV: development
    ports:
      - '3333:3333'
    volumes:
      - ./:/usr/app/computermaintenance
      - ./node_modules:/usr/app/computermaintenance/node_modules
    depends_on:
      - mongodb
      - neo4j
    links:
      - mongodb
      - neo4j
    tty: true

  mongodb:
    image: mongo
    container_name: 'MONGODB_COMPUTER_MAINTENANCE'
    ports:
      - '27017:27017'
    volumes:
      - ./data/db:/data/db
